version: '3.0'
services:
  project-worklow:
    image: registry.cn-shanghai.aliyuncs.com/alice52/practice-custom-test:20210608.09ec081
    restart: 'on-failure:3'
    container_name: dev-project-worklow
    volumes:
      - /root/dev-project-worklow/logs:/logs
    ports:
      - 8010:8080
    environment:
      - TZ=Asia/Shanghai
      - spring.profiles.active=cloud
