spring:
  profiles:
    # this sequence is master
    include: common-dev,uid-dev,common
  datasource:
    username: ENC(3+5Pg+H9L0s1ATmg/xTWLbNt9OeMFguochuRyTl9a4BGbD4lL2SLM8351rdHYhC2)
    password: ENC(MkGdNTchUL+OnF+nvm5YSSjWc7XeHLNab+KV9Wr3fqF1fAbEVLB2urZotLn8nAk1)
    url: ENC(IkyiSCpE0gO3ci8gj/oGV/sGJ+XurwiCanfUaih6U58LC56ZmRPdPud5L+eHQxSeSIC0+kwLdIAggsTLYz5oyDcpuu+e8uyB+k1j7tNto/ueRxMmWRqoh85YfaDF4RfUW4mT889AanpMxLIzWB+gpfQipAbMmwftSyttRlFnyyv4VnGQoevQBBTBNwdelAhpewqO+iPnLVBNE9zzgO5+RBLMXZSNx6j2EWxeqoi6wGk6WmNINP2aRre4uejnUcB89czJmhNOERLcoOU2BtKdhZxlFCoLCb5U6UTkG2PIUwx8vMQc1rax8AyqnJ/1R8pU3Ff7TcwgwJnw42YG/fte9DYPMYDKgP3DGygdVh7CpyUzZ8SRvv1NmigUrQ2ZvbTjGcZzf3PRn5AdjjEay1MmUtJgY7KRCZBvnVIhClT/nls=)
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20

