server:
  port: 9006

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  config:
    use-legacy-processing: true
  profiles:
    active: dev
  application:
    name: custom-test-redis